env:
  browser: true
  es2021: true
ignorePatterns:
  - "**/test/**"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project:
    - "tsconfig.json"
  ecmaFeatures:
    jsx: true
    modules: true
    experimentalObjectRestSpread: true
rules: { "indent": "off", "no-tabs": 0 }
